name: princess_diaries
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  table_calendar: ^3.0.9
  lottie: ^2.4.0
  intl: ^0.18.1
  curved_navigation_bar: ^1.0.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.4
  provider: ^6.0.5
  injectable: ^2.2.0
  get_it: ^7.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.6

flutter:

  uses-material-design: true
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
